### PR TITLE
Re-enable DHE-RSA and remove the ciphersuites table.

### LINKED ISSUE #295: Reinstate DHE-RSA cipher-suites and use better default DH parameters
So I was looking over the TLS code and I noticed that all the DHE cipher-suites were disabled as a result of PR #254. Why? To my knowledge, DHE-RSA is one of the more secure key exchange algorithms (second only to the elliptic curve version) and is enabled by default in most applications I've seen. It's also one of only 3 key exchange algorithms deemed secure enough for TLS 1.3:
https://en.wikipedia.org/wiki/Transport_Layer_Security#Key_exchange_or_key_agreement

In the commits disabling these cipher-suites, it was mentioned that SSL Labs said they were insecure. I suspect that this was due to the use of 1024-bit DH paremeters rather than DHE itself being broken. Changing `ssl_default_dhm_P` and `ssl_default_dhm_G` to use one of the common DHE parameter sets >= 2048-bits from `polarssl/dhm.h` should be ok (after you've reinstated DHE-RSA).

### PR DESCRIPTION
**Pull request by jcowgill**
Fixes #295 

This PR reworks a few things related to the ciphersuites list.

* Re-enable Ephemeral Diffie-Hellman (DHE) ciphersuites in polarssl.
* Use 2048-bit DH parameters by default (the ones from RFC5114). 4096-bit DH parameters are fairly rare are slow so I haven't used them.
* Add the legacy (`SSL_...`) ciphersuite names for DHE.
* Replace the ciphersuites table with a list of legacy ciphersuite mappings and use PolarSSL's lookup function to search for valid ciphersuites. As long as RC4 is disabled in polarssl, this should still only allow secure ciphersuites.

### CODE REVIEW

**Comment by jkarneges** [comment]
Thanks for the contribution. I haven't looked into it deeply yet, but just FYI it will likely need to be adjusted once #297 is merged.

**Comment by jcowgill** [comment]
Yes it would need a few adjustments for mbedTLS, but I don't think they've changed the ciphersuites API too much so it should be fairly easy. And thanks for doing the porting to mbedTLS, which was part of the reason I was looking at the code in the first place!

**Comment by jasom** [comment]
I reenabled some suites from #254.  I agree it was too aggresive, but I missed this one somehow.  Note also that 1024 bit DHE is actually secure so long as you don't use a common modulus, but this is something that is hard to get right by default.  I'll pull this with any needed changes as soon as #297 is merged.

**Comment by jasom** [comment]
Out of curiousity, why did you remove the table of mappings from old-names to new names?

**Comment by jasom** [comment]
@jkarneges will this change mess up your servers?  IIRC you are using system-provided mbedTLS, so rc4 may well be enabled.  Note that this change makes it so we no longer use a default list of ciphersuites, but instead by default allow all suites supported by the linked mbedTLS

**Comment by jcowgill** [comment]
Rebased to use mbedtls

**Comment by jasom** [comment]
The rebase didn't include updating the config patch; I fixed that.

**Comment by jcowgill** [comment]
Woops, thanks for fixing it!

**Pull request merged**
