### PR TITLE
Bug/gracefull shutdown

### PR DESCRIPTION
**Pull request by jasom**

### CODE REVIEW

**Comment by jkarneges** [comment]
I don't think SIGTERM should return code 1. That code is already used for other errors, and I'm not sure if I'd consider a clean exit from SIGTERM (even if non-graceful) to be an error. I'd vote changing the return code to 0 (or 2, if you really want the disambiguation).

Notably, this causes our launcher (which sends SIGTERM to mongrel2 on shutdown) to always report that mongrel2 exited with an error. Of course we could easily modify the launcher program to consider certain non-zero exit codes as non-errors, but it makes me pause.

**Comment by jasom** [comment]
How about this:

1) SIGTERM received once causes a clean shutdown and exit of 0
2) If a second SIGTERM is received before step one completes, it returns an exit code of 11 (same as SIGTERM)

**Comment by jkarneges** [comment]
What do you mean by code 11?

**Comment by jasom** [comment]
`exit(11)`

**Comment by jkarneges** [comment]
SIGTERM is code 15, if that's what you meant?

Aside from that, it sounds like you're suggesting that the first signal (whether SIGTERM or SIGINT) trigger a clean shutdown (same as current SIGINT handling), and if a second signal arrives during shutdown then the process exits immediately with a return code indicating which second signal was used. I'm good with this.

**Comment by jkarneges** [comment]
Also, I want to clarify that a clean shutdown is not waiting for connections to end, right? In our case we have streaming/websocket connections that may never end, so not waiting is our desired behavior.

(Eventually we should support some truly graceful or lingered shutdown mode that waits for connections to finish, but that could be a separate option.)

**Comment by jasom** [comment]
Yes, SIGTERM is 15; 11 is SIGSEGV.  My fault for commenting before my coffee.  Other than that we are on the same page and I'll update the PR this weekend.

**Comment by jasom** [comment]
Yes, SIGTERM is 15; 11 is SIGSEGV.  My fault for commenting before my coffee.  Other than that we are on the same page and I'll update the PR this weekend.

**Comment by jasom** [comment]
I updated this to return the signal that killed it upon a non-graceful exit.  A single SIGTERM (or SIGINT for that matter) should cause it to exit the main loop fairly expeditiously, and not trigger the non-graceful exit.  That logic was unreliable before.  Also #317 should be merged first, since whenever the close() actually happened to work to signal a graceful shutdown, a segfault would happen shortly afterwards.

**Comment by jkarneges** [comment]
@jasom 

1. I deleted your duplicate comment

2. It doesn't look like you implemented what you say in your Jan 6 comment. Did you forget to commit?

**Comment by jasom** [comment]
@jkarneges good catch, it was committed, but not pushed.

**Comment by jkarneges** [comment]
Hmm, you gonna push? :)

**Comment by jasom** [comment]
@jkarneges it's in 232c517; the history looks weird because github trusts the commit date.

**Comment by jkarneges** [comment]
I tested this and it seems good to me.

**Pull request merged**
