### PR TITLE
TCP keepalive enabled by default

### PR DESCRIPTION
**Pull request by godness84**

### CODE REVIEW

**Comment by jasom** [comment]
What is the motivation for this?  In real-world tests I haven't found long-polling to be reliable for over 15 minutes or so; I can't imagine that a 2 hour keep-alive would help in this case.

**Comment by godness84** [comment]
It can be useful when keepalive parameters are tweaked in order to know if the connection is broken within few minutes. In this way, the "ping/pong" mechanism would be implemented by the TCP stack, instead of implementing it by your own in the application layer.

For example, [Fanout Pushpin](http://pushpin.org/) - that is based on Mongrel2 - can't notify the backend server that the connection between pushpin and the client had been lost (within a normal time). Instead, enabling tcp keepalive on mongrel2 and tweaking the keepalive parameters it's possibile to know it within few minutes or more, if necessary.

**Comment by jasom** [comment]
I don't like it being on by default, but am happy to have this as a configuration option.

**Comment by jkarneges** [comment]
FWIW, we do this in our fork. https://github.com/fanout/mongrel2/commit/753554d548009b29965fff408690bca1ad736230

It could probably be adapted to be made optional.

**Comment by jasom** [comment]
@jkarneges is this running in production at fanout?  If so I'd consider it being enabled by default, though I still think an option is a good idea.

**Comment by jkarneges** [comment]
It is, yes.

In Nginx and HAProxy, it's optional and default off. Even though the feature is probably harmless and sometimes useful, I'd lean on default off if that's what others do.

**Comment by jkarneges** [comment]
Another thing, mongrel2 times out connections by default within a couple of minutes of inactivity. For a normal user of mongrel2, TCP keep alives would probably never come into play.

The issue at hand is Pushpin overrides this timeout (by sending keep-alive control messages to mongrel2 periodically) to allow quiet connections to exist indefinitely. So the only way to ensure dead connections are detected with Pushpin is to use TCP keep alives.

**Comment by jkarneges** [comment]
Submitted #313 for making this optional.

**Pull request closed without merging**
