### PR TITLE
chunked upload support

### PR DESCRIPTION
**Pull request by jkarneges**

### CODE REVIEW

**Comment by jasom** [comment]
My first thought was "how will this interact with MAX_CONTENT_LENGTH," and I see it just acts as if a chunked upload will be larger.  I think that's the simplest correct solution.

I like this implementation a lot.

Out of curiosity, when do clients send via chunked encoding in the wild?  I've not encountered this yet.

**Comment by jkarneges** [comment]
It was a strongly desired request from a Pushpin user needing to do large uploads. I believe it is needed if you are doing streaming gzip of the request body, since the Content-Length would be unknown in that case.

**Comment by jkarneges** [comment]
And yeah a larger buffer is needed to ensure we have enough room to process chunks (apparently there is no chunk size limit or standard so we just have to pick something large). I considered increasing MAX_CONTENT_LENGTH, but since chunked uploads will be very rare it didn't seem justifiable to make a major buffering change for the common case.

**Comment by dimovnike** [comment]
Hello, I have devices that send request using chunked transfers. They are under 2K size. Is there a way to configure it to process those as usual? I can not use upload storage I receive hundreds of small requests per seconds and I need to have workers on multiple servers.

**Comment by jkarneges** [comment]
Checking the code, it seems it is not possible to receive a "small" request body the normal way, if `Content-Length` is not specified.

The problem is that the body cannot be determined to be small until it is read. Probably this could be fixed in connection.c, in the block containing the Upload_file call, by attempting to read up to MAX_CONTENT_LENGTH chunked bytes beforehand, then being smart about what to do next. It's important that such buffering is not performed when `upload.stream` is enabled though.

I can't work on this, but I think it would be a reasonable PR.

The other idea is to use `upload.stream` with an adapter process that lives with mongrel2. IMO this is probably best anyway, because you could enforce body sizes without worry of large ones spilling over into files.

**Pull request merged**
